name: Greet on PR

on:
  pull_request:
    types: [opened, edited]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Edit all bot comments
        uses: actions/github-script@v6
        with:
          script: |
            const comments = await github.rest.issues.listComments({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            const botComments = comments.data.filter(c =>
              c.user.type === "Bot" &&
              c.body === "こんにちは！"
            );
            for (const c of botComments) {
              await github.rest.issues.updateComment({
                comment_id: c.id,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'これは編集したコメントです'
              });
            }