name: Greet on Pull Request

on:
  pull_request:
    types: [opened, edited]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Post greeting comment
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'こんにちは！'
            })